// <auto-generated />
using System;
using BookStoreAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreAPI.Migrations
{
    [DbContext(typeof(BookStoreDbContext))]
    [Migration("20231017042430_SecondMigration")]
    partial class SecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("BookStoreAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzerald",
                            Category = 2,
                            Description = "",
                            Price = 30.0,
                            PublishDate = new DateTime(2007, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Micheal Oliver",
                            Rating = 8.9000000000000004,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 2,
                            Author = "TMI",
                            Category = 4,
                            Description = "",
                            Price = 25.0,
                            PublishDate = new DateTime(2002, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Micheal Oliver",
                            Rating = 9.3000000000000007,
                            Title = "The Wrath of man"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Idoldev",
                            Category = 4,
                            Description = "",
                            Price = 25.0,
                            PublishDate = new DateTime(2002, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Micheal Oliver",
                            Rating = 8.0,
                            Title = "Hand of God"
                        },
                        new
                        {
                            Id = 4,
                            Author = "F. Scott Fitzerald",
                            Category = 0,
                            Description = "",
                            Price = 30.0,
                            PublishDate = new DateTime(2007, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Publisher = "Micheal Oliver",
                            Rating = 8.9000000000000004,
                            Title = "The Great Gatsby"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
